apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-ivyteam-io-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: docker-registry.ivyteam.io/engine-listing-service:latest
          ports:
            - containerPort: 80
